/******************************************************************************
 (C) COPYRIGHT TECHNOLUTION B.V., GOUDA NL
| =======          I                   ==          I    =
|    I             I                    I          I
|    I   ===   === I ===  I ===   ===   I  I    I ====  I   ===  I ===
|    I  /   \ I    I/   I I/   I I   I  I  I    I  I    I  I   I I/   I
|    I  ===== I    I    I I    I I   I  I  I    I  I    I  I   I I    I
|    I  \     I    I    I I    I I   I  I  I   /I  \    I  I   I I    I
|    I   ===   === I    I I    I  ===  ===  === I   ==  I   ===  I    I
|                 +---------------------------------------------------+
+----+            |  +++++++++++++++++++++++++++++++++++++++++++++++++|
     |            |             ++++++++++++++++++++++++++++++++++++++|
     +------------+                          +++++++++++++++++++++++++|
                                                        ++++++++++++++|
                                                                 +++++|

 -----------------------------------------------------------------------------
 Title      :  frenox_eth.h
 -----------------------------------------------------------------------------

 NOTE: This file is automatically generated by rdlc
       DO NOT EDIT!
******************************************************************************/

#ifndef FRENOX_ETH_H
#define FRENOX_ETH_H

/* Constants */
/* Relative addresses */
#define FRENOX_ETH_MAPPING_RX_BUFFER_OFFSET                                              0x00000000
#define FRENOX_ETH_MAPPING_TX_BUFFER_OFFSET                                              0x00001000
#define FRENOX_ETH_MAPPING_CONTROL_OFFSET                                                0x00002000
#define FRENOX_ETH_MAPPING_MDIO_OFFSET                                                   0x00002100

#define FRENOX_ETH_CONTROL_REGS_TX_SEND_NOW_OFFSET                                       0x00000000
#define FRENOX_ETH_CONTROL_REGS_TX_SEND_NOW_SIZE                                         0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_SEND_NOW_COUNT                                        0x00000001
#define FRENOX_ETH_CONTROL_REGS_TX_BUSY_OFFSET                                           0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_BUSY_SIZE                                             0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_BUSY_COUNT                                            0x00000001
#define FRENOX_ETH_CONTROL_REGS_TX_START_ADDR_OFFSET                                     0x00000008
#define FRENOX_ETH_CONTROL_REGS_TX_START_ADDR_SIZE                                       0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_START_ADDR_COUNT                                      0x00000001
#define FRENOX_ETH_CONTROL_REGS_TX_LEN_OFFSET                                            0x0000000C
#define FRENOX_ETH_CONTROL_REGS_TX_LEN_SIZE                                              0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_LEN_COUNT                                             0x00000001
#define FRENOX_ETH_CONTROL_REGS_TX_DONE_OFFSET                                           0x00000010
#define FRENOX_ETH_CONTROL_REGS_TX_DONE_SIZE                                             0x00000004
#define FRENOX_ETH_CONTROL_REGS_TX_DONE_COUNT                                            0x00000001
#define FRENOX_ETH_CONTROL_REGS_RX_ACK_PKT_OFFSET                                        0x00000020
#define FRENOX_ETH_CONTROL_REGS_RX_ACK_PKT_SIZE                                          0x00000004
#define FRENOX_ETH_CONTROL_REGS_RX_ACK_PKT_COUNT                                         0x00000001
#define FRENOX_ETH_CONTROL_REGS_RX_NEW_PKT_OFFSET                                        0x00000024
#define FRENOX_ETH_CONTROL_REGS_RX_NEW_PKT_SIZE                                          0x00000004
#define FRENOX_ETH_CONTROL_REGS_RX_NEW_PKT_COUNT                                         0x00000001
#define FRENOX_ETH_CONTROL_REGS_RX_START_ADDR_OFFSET                                     0x00000028
#define FRENOX_ETH_CONTROL_REGS_RX_START_ADDR_SIZE                                       0x00000004
#define FRENOX_ETH_CONTROL_REGS_RX_START_ADDR_COUNT                                      0x00000001
#define FRENOX_ETH_CONTROL_REGS_RX_LEN_OFFSET                                            0x0000002C
#define FRENOX_ETH_CONTROL_REGS_RX_LEN_SIZE                                              0x00000004
#define FRENOX_ETH_CONTROL_REGS_RX_LEN_COUNT                                             0x00000001
#define FRENOX_ETH_CONTROL_REGS_RX_BAD_PKT_OFFSET                                        0x00000030
#define FRENOX_ETH_CONTROL_REGS_RX_BAD_PKT_SIZE                                          0x00000004
#define FRENOX_ETH_CONTROL_REGS_RX_BAD_PKT_COUNT                                         0x00000001
#define FRENOX_ETH_CONTROL_REGS_PROMISCUOUS_OFFSET                                       0x00000040
#define FRENOX_ETH_CONTROL_REGS_PROMISCUOUS_SIZE                                         0x00000004
#define FRENOX_ETH_CONTROL_REGS_PROMISCUOUS_COUNT                                        0x00000001
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_LO_OFFSET                                         0x00000044
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_LO_SIZE                                           0x00000004
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_LO_COUNT                                          0x00000001
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_HI_OFFSET                                         0x00000048
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_HI_SIZE                                           0x00000004
#define FRENOX_ETH_CONTROL_REGS_MY_MAC_HI_COUNT                                          0x00000001

#define TL_REG_BUS_ID_BLOCK_ID_OFFSET                                                    0x00000000
#define TL_REG_BUS_ID_BLOCK_ID_SIZE                                                      0x00000004
#define TL_REG_BUS_ID_BLOCK_ID_COUNT                                                     0x00000001

#define SLAVE_INTERRUPT_REGISTER_BLOCK_ID_OFFSET                                         0x00000000
#define SLAVE_INTERRUPT_REGISTER_BLOCK_ID_SIZE                                           0x00000004
#define SLAVE_INTERRUPT_REGISTER_BLOCK_ID_COUNT                                          0x00000001
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_OFFSET                           0x00000004
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_SIZE                             0x00000004
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_COUNT                            0x00000001
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_OFFSET                           0x00000008
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_SIZE                             0x00000004
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_COUNT                            0x00000001
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_CLEAR_OFFSET                            0x0000000C
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_CLEAR_SIZE                              0x00000004
#define SLAVE_INTERRUPT_REGISTER_BLOCK_INTERRUPT_CLEAR_COUNT                             0x00000001

#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_OFFSET                        0x00000004
#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_SIZE                          0x00000004
#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_ENABLE_COUNT                         0x00000001
#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_OFFSET                        0x00000008
#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_SIZE                          0x00000004
#define SPLITTER_INTERRUPT_REGISTER_BLOCK_INTERRUPT_STATUS_COUNT                         0x00000001

/* Absolute addresses */
#define FRENOX_ETH_MAPPING_BASE                                                          0x00000000

#define FRENOX_ETH_MAPPING_RX_BUFFER_BASE                                                (FRENOX_ETH_MAPPING_BASE + FRENOX_ETH_MAPPING_RX_BUFFER_OFFSET)
#define FRENOX_ETH_MAPPING_RX_BUFFER_SIZE                                                0x00000800
#define FRENOX_ETH_MAPPING_RX_BUFFER_COUNT                                               1
#define FRENOX_ETH_MAPPING_TX_BUFFER_BASE                                                (FRENOX_ETH_MAPPING_BASE + FRENOX_ETH_MAPPING_TX_BUFFER_OFFSET)
#define FRENOX_ETH_MAPPING_TX_BUFFER_SIZE                                                0x00000800
#define FRENOX_ETH_MAPPING_TX_BUFFER_COUNT                                               1
#define FRENOX_ETH_MAPPING_CONTROL_BASE                                                  (FRENOX_ETH_MAPPING_BASE + FRENOX_ETH_MAPPING_CONTROL_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_SIZE                                                  0x00000100
#define FRENOX_ETH_MAPPING_CONTROL_COUNT                                                 1
#define FRENOX_ETH_MAPPING_CONTROL_TX_SEND_NOW_ADDRESS                                   (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_TX_SEND_NOW_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_TX_BUSY_ADDRESS                                       (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_TX_BUSY_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_TX_START_ADDR_ADDRESS                                 (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_TX_START_ADDR_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_TX_LEN_ADDRESS                                        (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_TX_LEN_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_TX_DONE_ADDRESS                                       (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_TX_DONE_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_RX_ACK_PKT_ADDRESS                                    (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_RX_ACK_PKT_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_RX_NEW_PKT_ADDRESS                                    (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_RX_NEW_PKT_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_RX_START_ADDR_ADDRESS                                 (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_RX_START_ADDR_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_RX_LEN_ADDRESS                                        (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_RX_LEN_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_RX_BAD_PKT_ADDRESS                                    (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_RX_BAD_PKT_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_PROMISCUOUS_ADDRESS                                   (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_PROMISCUOUS_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_MY_MAC_LO_ADDRESS                                     (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_MY_MAC_LO_OFFSET)
#define FRENOX_ETH_MAPPING_CONTROL_MY_MAC_HI_ADDRESS                                     (FRENOX_ETH_MAPPING_CONTROL_BASE + FRENOX_ETH_CONTROL_REGS_MY_MAC_HI_OFFSET)
#define FRENOX_ETH_MAPPING_MDIO_BASE                                                     (FRENOX_ETH_MAPPING_BASE + FRENOX_ETH_MAPPING_MDIO_OFFSET)
#define FRENOX_ETH_MAPPING_MDIO_SIZE                                                     0x00000080
#define FRENOX_ETH_MAPPING_MDIO_COUNT                                                    1

typedef struct _frenox_eth_control_regs_t {
    uint32_t tx_send_now;
    uint32_t tx_busy;
    uint32_t tx_start_addr;
    uint32_t tx_len;
    uint32_t tx_done;
    uint32_t padding1[3];
    uint32_t rx_ack_pkt;
    uint32_t rx_new_pkt;
    uint32_t rx_start_addr;
    uint32_t rx_len;
    uint32_t rx_bad_pkt;
    uint32_t padding2[3];
    uint32_t promiscuous;
    uint32_t my_mac_lo;
    uint32_t my_mac_hi;
} frenox_eth_control_regs_t;

typedef struct _tl_reg_bus_id_block_t {
    uint32_t id;
} tl_reg_bus_id_block_t;

typedef struct _slave_interrupt_register_block_t {
    uint32_t id;
    uint32_t interrupt_enable;
    uint32_t interrupt_status;
    uint32_t interrupt_clear;
} slave_interrupt_register_block_t;

typedef struct _splitter_interrupt_register_block_t {
    uint32_t padding1[1];
    uint32_t interrupt_enable;
    uint32_t interrupt_status;
} splitter_interrupt_register_block_t;

#define FRENOX_ETH_MAPPING_CONTROL ((volatile frenox_eth_control_regs_t *)0x00002000)

#endif /* FRENOX_ETH_H */
